// Loro — acervo instruction templates (context.md, AGENTS/CLAUDE, /loro-context
// skill, CODEOWNERS, PR template). Extracted from lib.rs for a cleaner core.
//
// Model: each domain lives in a single `context.md` (the official source of
// truth). Unconsolidated/contradictory/ambiguous knowledge is marked inline as
// HOTSPOTS inside that file — never as separate idea documents. Change proposals
// travel as a branch + Pull Request (the PR is the RFC); once approved they are
// merged into `context.md`. CODEOWNERS defines who approves each domain.

// Business-readable domain context (the final product, MARKDOWN).
// {{CONTEXT}} = context name. Section 6 (Hotspots) holds every not-yet-settled
// point (open questions, contradictions, ideas under study) as the evolution
// backlog of the domain. The lenses facts/thoughts/emotions/actions guide HOW
// the loop interprets material — they are not the file's structure.
pub const CONTEXT_TEMPLATE: &str = "# {{CONTEXT}} — contexto\n\n\
_Fonte oficial da verdade deste contexto (markdown, legível para negócio). Evolui por RFC (branch + PR) revisada pelos donos do contexto._\n\n\
## 0 · Sumário\n\n\
_Cartão de leitura rápida, regenerado pelo loop a cada atualização: 1 linha por seção + IDs-chave (`D-…`, `H-…`). Agentes: leiam este bloco primeiro e abram somente a seção necessária._\n\n(sem registros ainda)\n\n\
## 1 · Visão geral\n\n(sem registros ainda)\n\n\
## 2 · Como funciona\n\n(sem registros ainda)\n\n\
## 3 · Fluxos principais\n\n(sem registros ainda)\n\n\
## 4 · Quem participa e sistemas\n\n(sem registros ainda)\n\n\
## 5 · Decisões e fatos\n\n\
_Cada decisão recebe um ID estável `D-AAAA-MM-DD-<slug>`, endereçável por busca._\n\n(sem registros ainda)\n\n\
## 6 · Hotspots\n\n\
_Pontos de evolução ainda não consolidados — dúvidas em aberto, contradições entre fontes, temas ambíguos ou ideias em estudo. Cada hotspot é origem de reuniões, discussões e RFCs. Formato:_\n\n\
> [!HOTSPOT] H-<n> — título curto do ponto em aberto\n\
> O que está indefinido/contraditório e por quê.\n\n\
(sem registros ainda)\n";

pub const CONTEXT_TEMPLATE_EN: &str = "# {{CONTEXT}} — context\n\n\
_Official source of truth for this context (business-readable markdown). It evolves via RFC (branch + PR) reviewed by the context owners._\n\n\
## 0 · Summary\n\n\
_Quick-read card, regenerated by the loop on every update: 1 line per section + key IDs (`D-…`, `H-…`). Agents: read this block first and open only the section you need._\n\n(no records yet)\n\n\
## 1 · Overview\n\n(no records yet)\n\n\
## 2 · How it works\n\n(no records yet)\n\n\
## 3 · Main flows\n\n(no records yet)\n\n\
## 4 · Who takes part & systems\n\n(no records yet)\n\n\
## 5 · Decisions & facts\n\n\
_Each decision gets a stable, search-addressable ID `D-YYYY-MM-DD-<slug>`._\n\n(no records yet)\n\n\
## 6 · Hotspots\n\n\
_Evolution points not yet consolidated — open questions, contradictions between sources, ambiguous topics or ideas under study. Each hotspot seeds meetings, discussions and RFCs. Format:_\n\n\
> [!HOTSPOT] H-<n> — short title of the open point\n\
> What is undefined/contradictory and why.\n\n\
(no records yet)\n";

pub fn brain_claude_template(contexts: &[String]) -> String {
    let list = contexts
        .iter()
        .map(|c| format!("- `{c}`"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"# Acervo de contextos — gerado pelo Loro

Este diretório é autocontido: guarda o conhecimento estruturado, as instruções
do loop (este arquivo) e a skill `/loro-context` (`.claude/commands/loro-context.md`).
Um loop do Claude lê a **fila de geração de contexto** (`inbox/`), estrutura e
arquiva por contexto. Tudo é local; não copie dados pessoais sensíveis para os
registros. (Fluxo do Loro: brainstorming → fila → contexto; esta skill é o passo
fila → contexto.)

## Contextos deste acervo
{list}

(a lista vive em `~/.loro/config.json`; gerencie pela aba "acervo" do Loro.
Contextos são **recursivos**: um domínio é uma pasta com `context.md` +
`CHANGELOG.md` que **pode conter subdomínios** — pastas-filhas na MESMA estrutura,
recursivamente (ex.: `frota/`, `frota/multas/`, `frota/eletrica/piloto/`). Cada
segmento é um slug minúsculo; a árvore vai até 6 níveis.)

## Estrutura (um arquivo por domínio)
- `inbox/` — entrada CRUA do loop: transcrições do Loro **ou qualquer texto/nota
  avulsa** (`.md`/`.txt`) que você soltar aqui · `processed/` — cruas já processadas
- `inbox/_prompt.md` — **guia opcional**: se existir, siga-o ANTES do processamento
  padrão (só afeta os itens pendentes)
- `reunioes/` — registro estruturado por reunião (markdown; fonte efêmera) ·
  `notas/` — registro estruturado de textos avulsos que não são reuniões
- `contextos/<c>/context.md` — **FONTE OFICIAL DA VERDADE**: o contexto do domínio
- `contextos/<c>/CHANGELOG.md` — histórico datado, append-only
- `contextos/<c>/<subdomínio>/` — subdomínio: MESMA estrutura (`context.md` +
  `CHANGELOG.md`), recursivamente. Um domínio grande vira pai-índice + subdomínios.
- `.github/CODEOWNERS` — dono(s) de cada contexto (quem aprova RFCs)
- `.github/pull_request_template.md` — o corpo da RFC (usado ao propor mudança)
- `INDEX.md` — navegação · `.brain/` — estado e atividade do loop

Regra geral: **tudo é markdown**; o conhecimento consolidado vive **só** no
`context.md`. Materiais de apoio (gravações, apresentações, docs de reunião) são
efêmeros: apenas referenciados, nunca a fonte da verdade.

## Tipos de contexto (domínio × prática)
Há duas naturezas — o loop escolhe o molde do `context.md` pelo caminho:
- **Domínio** (negócio: o *quê* — ex.: `frota`, `assinatura`): 6 seções de negócio.
- **Prática** (forma de trabalho: o *como* — tudo sob `engenharia/`): mesmas seções,
  descrevendo práticas/ferramentas/decisões técnicas.

## Hotspots (em vez de documentos de ideia)
Ideias **não** viram arquivos soltos. Todo conteúdo ainda não consolidado —
dúvida em aberto, contradição entre fontes, tema ambíguo, ideia em estudo — é
registrado como **hotspot** dentro da seção 6 do `context.md`, no formato:

> [!HOTSPOT] H-<n> — título curto
> O que está em aberto e por quê.

Os hotspots são o backlog de evolução do domínio: origem de reuniões, discussões
e RFCs. Uma ideia só é **promovida** a fato (seções 1–5) via RFC aprovada.

## Ideia = RFC = branch + PR (evolução do conhecimento)
Uma proposta de mudança **não** é um documento: é uma RFC materializada como uma
branch + Pull Request. A mudança é aplicada direto no `context.md` (+ CHANGELOG);
o PR (título/corpo pelo `pull_request_template.md`) **é** a RFC. Os donos do
contexto (`CODEOWNERS`) revisam e aprovam; ao fazer merge na `main`, a proposta
vira a nova fonte oficial da verdade. Você (loop) NÃO abre PRs — quem versiona e
propõe é a pessoa, pelos botões "Versionar" e "Propor mudança" do Loro.

## Como interpretar o material (as quatro lentes)
Ao ler cada fonte, separe **fatos** (concreto/decidido → seções 1–5),
**pensamentos** (hipóteses/dúvidas → hotspots), **emoções** (sentimento do grupo:
tensões, riscos percebidos) e **ações** (o que fazer, com responsável e prazo).
Isso guia PARA ONDE cada coisa vai — não é a estrutura de saída. Participantes são
descritos por **arquétipo** (produto, negócio, engenharia), não por área.

## O produto final (`contextos/<c>/context.md`)
Markdown **acessível para negócio** (sem jargão técnico/DDD), com seções fixas:
0 Sumário · 1 Visão geral · 2 Como funciona · 3 Fluxos principais · 4 Quem
participa e sistemas · 5 Decisões e fatos · 6 Hotspots. Mantenha os títulos; sem
informação, use `(sem registros ainda)`. Consolidado derivado do CHANGELOG +
fontes (seguro reescrever seções 0–5; fontes são efêmeras). O que não estiver
consolidado vira hotspot, nunca é inventado como fato.

**IDs estáveis (ADR-0004).** Cada decisão da seção 5 recebe um ID
`D-AAAA-MM-DD-<slug>`; cada hotspot da seção 6 recebe `H-<n>` (numeração local ao
arquivo, nunca reusada). IDs tornam qualquer item endereçável por busca — cite-os
no CHANGELOG e no `INDEX.md`.

## Leitura eficiente (protocolo — ADR-0004)
Estrutura existe para que ler seja barato. Ao consultar o acervo:
1. Comece pelo `INDEX.md` (o mapa) e escolha o(s) contexto(s) pela descrição.
2. Leia o **Sumário (§0)** do `context.md` — a maioria das consultas para aqui.
3. Localize IDs (`D-…`, `H-…`) com busca (grep) e leia somente a seção necessária.
4. O arquivo inteiro é o último recurso, não o primeiro.

Formato da linha do `INDEX.md` (uma por contexto, regenerada pelo loop):
`- **<contexto>** — <descrição em 1 frase> · atualizado AAAA-MM-DD · hotspots H-1..H-<n>`

## Estilo (IMPORTANTE)
Prosa de documentação — parágrafos claros e completos — e não bullets soltos
(tabelas e listas curtas são bem-vindas quando estruturam melhor). Entrada de
CHANGELOG: `## AAAA-MM-DD — <título>` + 1–3 parágrafos. **NÃO referencie o arquivo
de reunião** (fonte efêmera, não versionada); escreva de forma autossuficiente.

**Escrita objetiva do NEGÓCIO (regra dura).** O documento descreve o **domínio**,
nunca o processo. NÃO cite metodologia nem mecânica interna do acervo (DDD,
"reestruturação/quebra/separação/migração", "varredura/pull fresh", "conector",
"gerado a partir de Jira/Confluence/Slack", "não de um `context.md` anterior").
Evite **desambiguação por negação** ("não é um X", "não confundir com", "apesar do
nome"): afirme o que a coisa é. Dúvida real de negócio vira **hotspot curto** (§6),
não narração no corpo. O CHANGELOG registra a evolução do **conhecimento/decisões
do domínio**, não a ferramenta nem o passo de reestruturação.

## Regras do loop
0. **Guia opcional:** se `inbox/_prompt.md` existir, leia e siga-o ANTES de tudo.
1. Processar apenas arquivos novos de `inbox/` (fora de `.brain/state.json`).
   Aceita qualquer arquivo legível. Ignore `inbox/_prompt.md`.
2. **Direcionamento explícito:** arquivo com nome `<contexto>--<nome>` pertence
   àquele contexto — respeite. Sem prefixo, classifique pelo conteúdo. Se nenhum
   contexto existente couber, **sugira criar um novo** (não force o encaixe).
3. Classificar a origem: reunião → `reunioes/`; documento/nota → `notas/`. Gerar
   o registro estruturado em markdown.
4. **Append-only** no CHANGELOG. Conhecimento consolidado atualiza `context.md`
   (seções 1–5); o não-consolidado vira **hotspot** (seção 6). Nunca crie arquivos
   de ideia. Cru movido p/ `processed/`, nunca apagado.
5. Regenerar o `context.md` dos contextos tocados (seções 0–6), incluindo o
   **Sumário (§0)** e os IDs estáveis (`D-…`, `H-…`). Use as lentes só para
   INTERPRETAR.
6. Atualizar `INDEX.md` (no formato de linha enriquecida do protocolo de
   leitura), `state.json` e `.brain/activity.log`. Idempotente; na
   dúvida de contexto, NÃO assuma: registre a incerteza como hotspot com `?`
   e só destine o item quando a evidência for clara.
7. **Quebra em subdomínios (DDD):** quando um domínio virar um COMPOSTO de
   bounded contexts (vários fluxos/fronteiras distintos), quebre-o em subdomínios
   `contextos/<c>/<sub>/` — cada um com seu `context.md` + `CHANGELOG.md`. O
   `context.md` do PAI vira overview + índice dos subdomínios + fatos transversais;
   o detalhe desce para os filhos. Fixe a "casa canônica" de temas transversais
   (ex.: multas) num só subdomínio e trate os demais como sobreposição.

## Respeite a estrutura existente
Se o acervo/contexto já tem estrutura própria (arquivos, subpastas), **entenda e
respeite** — só complete o que faltar, nunca sobrescreva o que já existe. Loro é
um **companheiro** do seu fluxo/agentes, não os substitui.
"#
    )
}

// /loro-context skill written INSIDE the acervo (the directory is self-contained).
// ADR-0013: it is the queue → context step of the brainstorming → queue → context flow.
pub const BRAIN_SKILL: &str = r#"---
description: Gera contexto a partir da fila (inbox) — reuniões, relatórios e textos viram context.md + CHANGELOG.md
---

Você é o curador deste acervo de conhecimento. Leia `AGENTS.md` (ou `CLAUDE.md`)
na raiz do acervo — ele define estrutura, estilo, a fonte oficial da verdade
(`context.md`), os hotspots e as regras — e siga-o à risca. Trabalhe somente
dentro desta pasta.

0. Se `inbox/_prompt.md` existir, siga-o ANTES do processamento padrão. Ao
   terminar, **arquive-o** em `.brain/prompt-history/<AAAA-MM-DD-HHMM>.md` e
   **remova** `inbox/_prompt.md` (o histórico não é versionado).
0.5. Leia `.loro/settings.json` se existir (`{"autoContext": bool}`) — ausente
   ou ilegível conta como `true` (padrão). Esse valor é a permissão para criar
   um contexto NOVO sozinho (ADR-0006); nunca afeta atribuir a um contexto
   já existente.
1. Leia `.brain/state.json`; liste `inbox/` e filtre o que ainda não foi processado (ignore `_prompt.md`).
2. Nada novo? Responda `brain: nada novo` e encerre.
3. Para cada arquivo novo: se o nome tiver prefixo `<contexto>--`, direcione
   àquele contexto (pode ser hierárquico `area/sub`); senão classifique pelo
   conteúdo. Se nenhum contexto existente couber: com `autoContext: true`,
   **crie um contexto novo** livremente; com `autoContext: false`, **NÃO
   crie** — deixe o item em `inbox/` (não mova para `processed/`) e relate ao
   final que ele precisa de um contexto atribuído manualmente pela pessoa.
   Quando for criar ou atribuir: classifique a origem (reunião × documento/nota),
   gere o registro em `reunioes/` ou `notas/`, acrescente entrada em prosa no
   `contextos/<c>/CHANGELOG.md`, e **atualize o `contextos/<c>/context.md`**: o
   consolidado nas seções 1–5, o que ainda estiver em aberto/contraditório como
   **hotspot** na seção 6. Nunca crie arquivos de ideia. **Nunca referencie o
   arquivo de reunião** (fonte efêmera). Se o domínio virar um COMPOSTO (DDD),
   quebre em subdomínios `contextos/<c>/<sub>/` (mesma estrutura, recursiva); o
   pai vira overview+índice.
4. Mova o cru para `processed/` (exceto os itens deixados pendentes no passo 3),
   atualize `state.json`, anexe em `.brain/activity.log` e atualize `INDEX.md`.
5. Respeite estrutura já existente (só complete lacunas; nunca sobrescreva). Não
   abra PRs nem versione: quem propõe mudança é a pessoa, pelos botões do Loro.
6. Ao final, informe em 1–2 linhas o que fez.

Regras de rigor (ADR-0002 §5):
- **Nunca assuma premissas** não declaradas. O que não estiver na base ou no
  pedido é incerteza: registre-a explicitamente (hotspot/`?` ou uma linha de
  "incertezas" na resposta) e, quando a interação permitir, pergunte.
- **Varredura eficiente:** para listar/ler muitos arquivos, delegue a leitura a
  subagentes (Task) com um modelo rápido (ex.: Haiku), recebendo só o essencial;
  reserve o modelo principal para a síntese.
- **Leitura barata (ADR-0004):** comece pelo `INDEX.md` e pelo Sumário (§0) de
  cada `context.md`; localize IDs estáveis (`D-…`, `H-…`) com busca e leia
  somente a seção necessária — o arquivo inteiro é o último recurso.
"#;

// ---- English variants (selected by the project language) ----

pub fn agents_template_en(contexts: &[String]) -> String {
    let list = contexts
        .iter()
        .map(|c| format!("- `{c}`"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"# Knowledge base — generated by Loro

This directory is self-contained: it holds the structured knowledge, the loop
instructions (this file) and the `/loro-context` skill
(`.claude/commands/loro-context.md`). A Claude loop reads the **context-generation
queue** (`inbox/`), structures it and files it by context. Everything is local; do
not copy sensitive personal data into the records. (Loro's flow: brainstorming →
queue → context; this skill is the queue → context step.)

## Contexts in this base
{list}

(the list lives in `~/.loro/config.json`; manage it from Loro's "acervo" tab.
Contexts are **recursive**: a domain is a folder with `context.md` + `CHANGELOG.md`
that **may contain subdomains** — child folders in the SAME shape, recursively
(e.g. `frota/`, `frota/multas/`, `frota/eletrica/piloto/`). Each segment is a
lowercase slug; the tree goes up to 6 levels.)

## Structure (one file per domain)
- `inbox/` — raw loop input (Loro transcripts or any dropped `.md`/`.txt`) ·
  `processed/` — raw already processed
- `inbox/_prompt.md` — **optional guide**: if present, follow it BEFORE the default
  processing (affects only the pending items); archive & clear it after the run
- `reunioes/` — structured record per meeting (ephemeral source) · `notas/` —
  structured record for standalone notes
- `contextos/<c>/context.md` — **OFFICIAL SOURCE OF TRUTH**: the domain context
- `contextos/<c>/CHANGELOG.md` — dated history, append-only
- `contextos/<c>/<subdomain>/` — subdomain: SAME shape (`context.md` +
  `CHANGELOG.md`), recursively. A large domain becomes a parent-index + subdomains.
- `.github/CODEOWNERS` — owner(s) of each context (who approves RFCs)
- `.github/pull_request_template.md` — the RFC body (used when proposing a change)

Consolidated knowledge lives **only** in `context.md`. Supporting material
(recordings, decks, meeting docs) is ephemeral: referenced, never the truth.

## Hotspots (instead of idea documents)
Ideas are **not** loose files. Anything not yet consolidated — open question,
contradiction between sources, ambiguous topic, idea under study — is recorded as
a **hotspot** inside section 6 of `context.md`:

> [!HOTSPOT] H-<n> — short title
> What is open and why.

Hotspots are the domain's evolution backlog: they seed meetings, discussions and
RFCs. An idea is only **promoted** to fact (sections 1–5) via an approved RFC.

## Idea = RFC = branch + PR
A change proposal is **not** a document: it is an RFC materialized as a branch +
Pull Request. The change is applied directly to `context.md` (+ CHANGELOG); the PR
(title/body from `pull_request_template.md`) **is** the RFC. The context owners
(`CODEOWNERS`) review and approve; merging into `main` makes it the new source of
truth. You (the loop) do NOT open PRs — the person versions and proposes via
Loro's "Versionar" and "Propor mudança" buttons.

## Interpretation lens (facts / thoughts / emotions / actions)
Read each source separating facts (concrete/decided → sections 1–5), thoughts
(hypotheses/open questions → hotspots), emotions (group sentiment/risks) and
actions (owner + deadline). This guides WHERE things go. Describe participants by
**archetype** (product, business, engineering), not by department.

## Final product (`contextos/<c>/context.md`)
Business-readable markdown (no DDD jargon), fixed sections: Summary · Overview ·
How it works · Main flows · Who takes part & systems · Decisions & facts ·
Hotspots. Keep the titles; with no info use `(no records yet)`. Never invent
facts — unconsolidated material becomes a hotspot.

**Stable IDs (ADR-0004).** Each decision in section 5 gets an ID
`D-YYYY-MM-DD-<slug>`; each hotspot in section 6 gets `H-<n>` (numbering local to
the file, never reused). IDs make any item search-addressable — cite them in the
CHANGELOG and in `INDEX.md`.

## Efficient reading (protocol — ADR-0004)
Structure exists so that reading stays cheap. When consulting the base:
1. Start from `INDEX.md` (the map) and pick the context(s) by description.
2. Read the `context.md` **Summary (§0)** — most queries stop here.
3. Locate IDs (`D-…`, `H-…`) via search (grep) and read only the needed section.
4. The whole file is the last resort, not the first.

`INDEX.md` line format (one per context, regenerated by the loop):
`- **<context>** — <1-sentence description> · updated YYYY-MM-DD · hotspots H-1..H-<n>`

**Objective BUSINESS writing (hard rule).** Describe the **domain**, never the
process. Do not cite methodology or acervo internals (DDD, "restructuring/split/
migration", "fresh sweep/pull", "connector", "generated from Jira/Confluence/Slack",
"not from a prior `context.md`"). Avoid **disambiguation-by-negation** ("it is not
an X", "not to be confused with", "despite the name"): state what the thing is. A
real business open question becomes a short **hotspot** (§6), not body narration.
The CHANGELOG records the evolution of the domain's **knowledge/decisions**, not
the tooling or the restructuring step.

## Loop rules
0. If `inbox/_prompt.md` exists, follow it first; then archive it to
   `.brain/prompt-history/` and remove it (not versioned).
1. Process only new files in `inbox/` (ignore `_prompt.md`).
2. `<context>--name` prefix routes a file to that context. With no fitting
   context, **suggest creating a new one** — do not force the fit.
3. Meeting transcript -> `reunioes/`; note/document -> `notas/`.
4. Append-only CHANGELOG; consolidated knowledge updates `context.md` (1–5),
   the rest becomes a **hotspot** (section 6). Never create idea files. Raw moved
   to `processed/`, never deleted.
5. Regenerate the touched `context.md` (sections 0–6), including the
   **Summary (§0)** and the stable IDs (`D-…`, `H-…`).
6. Update `INDEX.md` (using the reading protocol's enriched line format),
   `state.json`, `.brain/activity.log`. Idempotent; when in
   doubt about the context, do NOT assume: record the uncertainty as a `?`
   hotspot and only file the item when the evidence is clear.
7. **Split into subdomains (DDD):** when a domain becomes a COMPOSITE of bounded
   contexts, split it into `contextos/<c>/<sub>/` subdomains — each with its own
   `context.md` + `CHANGELOG.md`. The PARENT `context.md` becomes an overview +
   index of its subdomains + cross-cutting facts; detail moves down. Pin the
   canonical home of a cross-cutting topic (e.g. fines) to one subdomain.

## Respect existing structure
If a base/context already has its own structure, understand and respect it — only
fill gaps, never overwrite. Loro is a **companion** to your workflow/agents.
"#
    )
}

pub const BRAIN_SKILL_EN: &str = r#"---
description: Generates context from the queue (inbox) — meetings, reports and notes become context.md + CHANGELOG.md
---

You are the curator of this knowledge base. Read `AGENTS.md` (or `CLAUDE.md`) at
the base root — it defines the structure, style, source of truth (`context.md`),
hotspots and rules — and follow it strictly. Work only inside this folder.

0. If `inbox/_prompt.md` exists, follow it BEFORE default processing; then archive
   it to `.brain/prompt-history/<YYYY-MM-DD-HHMM>.md` and remove it (not versioned).
0.5. Read `.loro/settings.json` if present (`{"autoContext": bool}`) — absent or
   unreadable counts as `true` (default). This is the permission to create a
   NEW context on its own (ADR-0006); it never affects assigning to an
   existing context.
1. Read `.brain/state.json`; list `inbox/` and filter unprocessed (ignore `_prompt.md`).
2. Nothing new? Reply `brain: nothing new` and stop.
3. For each new file: honor a `<context>--` prefix; else classify by content.
   If no existing context fits: with `autoContext: true`, **create a new
   context** freely; with `autoContext: false`, **do NOT create one** — leave
   the item in `inbox/` (do not move it to `processed/`) and report at the end
   that it needs a context assigned manually by the person. When creating or
   assigning: classify (meeting vs note), write the structured record in
   `reunioes/` or `notas/`, append a prose entry to `contextos/<c>/CHANGELOG.md`,
   and **update `contextos/<c>/context.md`**: consolidated knowledge in
   sections 1–5, anything still open/contradictory as a **hotspot** in section
   6. Never create idea files. **Never reference the meeting file** (ephemeral,
   unversioned). If the domain becomes a COMPOSITE (DDD), split it into
   `contextos/<c>/<sub>/` subdomains (same recursive shape); the parent becomes
   an overview + index.
4. Move raw to `processed/` (except items left pending in step 3), update
   `state.json`, append to `.brain/activity.log`, update `INDEX.md`.
5. Respect existing structure (fill gaps only; never overwrite). Do not open PRs
   or version: the person proposes changes via Loro's buttons.
6. Finish with a 1–2 line summary of what you did.

Rigor rules (ADR-0002 §5):
- **Never assume unstated premises.** Anything not in the base or in the request
  is an uncertainty: record it explicitly (hotspot/`?` or an "uncertainties"
  line in the answer) and, when the interaction allows, ask.
- **Efficient scanning:** to list/read many files, delegate reading to subagents
  (Task) on a fast model (e.g. Haiku) returning only the essentials; keep the
  main model for synthesis.
- **Cheap reading (ADR-0004):** start from `INDEX.md` and each `context.md`
  Summary (§0); locate stable IDs (`D-…`, `H-…`) via search and read only the
  needed section — the whole file is the last resort.
"#;

// ---- meeting-AI skills run by the terminal Claude (ADR-0012) ----
//
// The meeting AI is NOT a Rust model spawn: it is a Claude Code skill the
// terminal-resident Claude runs (the /brain pattern). The app injects the
// invocation into the terminal PTY; the skill READS the meeting's live stream
// (reuniao.md + manifest.json + relevant contextos/) and responds. It uses
// Claude Code's own Read/Write tools (no loro IPC) and MUST NOT edit
// manifest.json — the app owns it with an atomic writer (ADR-0012), and editing
// it here would race that writer. `$ARGUMENTS` carries the meeting directory
// (acervo-relative), so the skills render with a meeting-dir placeholder.

pub const MEETING_ANALYSE_SKILL: &str = r#"---
description: Analisa a reunião ao vivo e escreve investigação + relatório objetivos (ADR-0012)
argument-hint: <dir-da-reuniao>
---

Diretório da reunião (relativo à raiz do acervo): `$ARGUMENTS`

Você é o analista de reunião do Loro (ADR-0012). Trabalhe SOMENTE dentro do
diretório acima. Use apenas suas próprias ferramentas Read/Write — não chame IPC
do loro e NÃO edite `manifest.json` (o app é o dono e o escreve de forma atômica;
editar aqui geraria corrida com esse escritor).

1. **Investigue PRIMEIRO no contexto LOCAL.** Leia `$ARGUMENTS/reuniao.md` (a
   transcrição AO VIVO, que cresce durante a reunião), `$ARGUMENTS/manifest.json`
   (metadados + marcadores sem PII) e o(s) `contextos/<c>/context.md` claramente
   relevante(s) — a base de conhecimento LOCAL é sempre a primeira fonte. Não leia
   a transcrição de outra reunião nem notas em `brainstorming/` para as quais você
   não foi apontado (BR-8).
2. **SOMENTE DEPOIS** de esgotar o que a base local oferece, se ainda faltar
   evidência, você PODE buscar em fontes externas (internet, MCP, qualquer lugar).
   Deixe claro no resultado o que veio da base local e o que veio de fora.
3. Produza, de forma OBJETIVA (prosa de negócio, sem metodologia): tema
   predominante, decisões, riscos, inconsistências e perguntas sugeridas.
4. Escreva o resultado em `$ARGUMENTS/artefatos/investigacoes/analise-<ISO>.md`
   (carimbo ISO 8601 em UTC, ex.: `analise-2026-07-27T1430Z.md`).
5. Registre estatísticas SEM PII: para cada dúvida/decisão/investigação/pergunta
   identificada, acrescente UMA linha JSON em `$ARGUMENTS/marcadores.jsonl` no
   formato `{"tipo":"decisao","ref":"artefatos/investigacoes/analise-<ISO>.md"}`
   (só `tipo` + `t_ms?`/`ref?`, NUNCA texto de transcrição). O app incorpora esses
   marcadores ao relatório — não edite `manifest.json`.
6. Atualize `$ARGUMENTS/relatorio.md`: substitua a prosa provisória das seções
   `## Resumo`, `## Decisões` e `## Dúvidas & Respostas` (ou suas equivalentes em
   inglês: `## Summary`, `## Decisions`, `## Questions & Answers` — o notebook
   pode ter nascido em qualquer um dos dois idiomas) por prosa real e objetiva
   derivada da transcrição, mantendo os títulos existentes. Se `relatorio.md`
   ainda não existir, crie-o com essas seções no idioma deste skill.
7. Acrescente UMA linha JSON, orientada a evento, em `$ARGUMENTS/auditoria.jsonl`
   registrando o que leu e produziu — nunca texto de transcrição, PII ou segredos
   (BR-8/BR-9), ex.:
   `{"em":"<ISO>","event":"analyse","read":["reuniao.md","manifest.json"],"wrote":["artefatos/investigacoes/analise-<ISO>.md","relatorio.md","marcadores.jsonl"]}`.

Ao final, responda em pt-BR com 1–2 linhas do que você escreveu.

Regras de rigor (ADR-0002 §5):
- **Nunca assuma premissas** não declaradas. O que não estiver na base ou no
  pedido é incerteza: registre-a explicitamente (hotspot/`?` ou uma linha de
  "incertezas" na resposta) e, quando a interação permitir, pergunte.
- **Varredura eficiente:** para listar/ler muitos arquivos, delegue a leitura a
  subagentes (Task) com um modelo rápido (ex.: Haiku), recebendo só o essencial;
  reserve o modelo principal para a síntese.
- **Leitura barata (ADR-0004):** comece pelo `INDEX.md` e pelo Sumário (§0) de
  cada `context.md`; localize IDs estáveis (`D-…`, `H-…`) com busca e leia
  somente a seção necessária — o arquivo inteiro é o último recurso.
"#;

pub const MEETING_QUESTION_SKILL: &str = r#"---
description: Responde de forma objetiva a uma pergunta sobre a reunião ao vivo (ADR-0012)
argument-hint: <dir-da-reuniao> <pergunta>
---

Argumentos: `$ARGUMENTS`
O PRIMEIRO token é o diretório da reunião (relativo à raiz do acervo); o RESTANTE
é a pergunta.

Você é o assistente de reunião do Loro (ADR-0012). Trabalhe SOMENTE dentro desse
diretório. Use apenas suas próprias ferramentas Read/Write — não chame IPC do loro
e NÃO edite `manifest.json` (o app é o dono; editar aqui geraria corrida com o
escritor atômico).

1. **Investigue PRIMEIRO no contexto LOCAL:** leia `<dir>/reuniao.md` (a
   transcrição AO VIVO), `<dir>/manifest.json` e o(s) `contextos/<c>/context.md`
   claramente relevante(s) — a base LOCAL é sempre a primeira fonte. Não leia a
   transcrição de outra reunião nem notas em `brainstorming/` para as quais não foi
   apontado (BR-8).
2. Responda à pergunta de forma OBJETIVA, ancorada no que a reunião e a base local
   de fato dizem. **SOMENTE DEPOIS** de esgotar a base local, se ainda faltar
   evidência, você PODE buscar em fontes externas (internet, MCP, qualquer lugar) —
   deixando claro o que veio de fora. Se nada resolver, diga isso claramente.
3. Quando um artefato escrito ajudar (uma tabela, uma nota curta), escreva-o em
   `<dir>/artefatos/respostas/<slug>.md` e referencie-o na resposta.
4. Acrescente UMA linha JSON sem PII em `<dir>/auditoria.jsonl` (evento `answer`,
   o que leu/produziu — nunca texto de transcrição, PII ou segredos: BR-8/BR-9).

Responda em pt-BR.

Regras de rigor (ADR-0002 §5):
- **Nunca assuma premissas** não declaradas. O que não estiver na base ou no
  pedido é incerteza: registre-a explicitamente (hotspot/`?` ou uma linha de
  "incertezas" na resposta) e, quando a interação permitir, pergunte.
- **Varredura eficiente:** para listar/ler muitos arquivos, delegue a leitura a
  subagentes (Task) com um modelo rápido (ex.: Haiku), recebendo só o essencial;
  reserve o modelo principal para a síntese.
- **Leitura barata (ADR-0004):** comece pelo `INDEX.md` e pelo Sumário (§0) de
  cada `context.md`; localize IDs estáveis (`D-…`, `H-…`) com busca e leia
  somente a seção necessária — o arquivo inteiro é o último recurso.
"#;

pub const MEETING_ANALYSE_SKILL_EN: &str = r#"---
description: Analyses the live meeting and writes an objective investigation + report (ADR-0012)
argument-hint: <meeting-dir>
---

Meeting directory (relative to the acervo root): `$ARGUMENTS`

You are Loro's meeting analyst (ADR-0012). Work ONLY inside the directory above.
Use only your own Read/Write tools — do not call loro IPC and do NOT edit
`manifest.json` (the app owns it and writes it atomically; editing it here would
race that writer).

1. **Investigate the LOCAL context FIRST.** Read `$ARGUMENTS/reuniao.md` (the LIVE
   transcript, accreting during the meeting), `$ARGUMENTS/manifest.json` (metadata
   + PII-free markers) and the clearly relevant `contextos/<c>/context.md` — the
   LOCAL knowledge base is always the first source. Do not read any other meeting's
   transcript or `brainstorming/` notes you were not pointed at (BR-8).
2. **ONLY AFTER** exhausting the local base, if evidence is still missing, you MAY
   search external sources (internet, MCP, anywhere). Make clear what came from the
   local base and what came from outside.
3. Produce, OBJECTIVELY (business prose, no methodology talk): predominant theme,
   decisions, risks, inconsistencies and suggested questions.
4. Write the result to `$ARGUMENTS/artefatos/investigacoes/analise-<ISO>.md`
   (ISO 8601 UTC stamp, e.g. `analise-2026-07-27T1430Z.md`).
5. Record PII-free stats: for each doubt/decision/investigation/question, append
   ONE JSON line to `$ARGUMENTS/marcadores.jsonl` like
   `{"tipo":"decisao","ref":"artefatos/investigacoes/analise-<ISO>.md"}` (only
   `tipo` + `t_ms?`/`ref?`, NEVER transcript text). The app folds these markers
   into the report — do not edit `manifest.json`.
6. Update `$ARGUMENTS/relatorio.md`: replace the placeholder prose in the
   `## Summary`, `## Decisions` and `## Questions & Answers` sections (or their
   pt equivalents `## Resumo`, `## Decisões`, `## Dúvidas & Respostas` — the
   notebook may have been born in either language) with real, objective prose
   derived from the transcript, keeping the existing titles. If `relatorio.md`
   does not exist yet, create it with those sections in this skill's language.
7. Append ONE event-oriented JSON line to `$ARGUMENTS/auditoria.jsonl` recording
   what you read and produced — never transcript text, PII or secrets (BR-8/BR-9).

Finish with a 1–2 line summary (in English) of what you wrote.

Rigor rules (ADR-0002 §5):
- **Never assume unstated premises.** Anything not in the base or in the request
  is an uncertainty: record it explicitly (hotspot/`?` or an "uncertainties"
  line in the answer) and, when the interaction allows, ask.
- **Efficient scanning:** to list/read many files, delegate reading to subagents
  (Task) on a fast model (e.g. Haiku) returning only the essentials; keep the
  main model for synthesis.
- **Cheap reading (ADR-0004):** start from `INDEX.md` and each `context.md`
  Summary (§0); locate stable IDs (`D-…`, `H-…`) via search and read only the
  needed section — the whole file is the last resort.
"#;

pub const MEETING_QUESTION_SKILL_EN: &str = r#"---
description: Answers a question about the live meeting objectively (ADR-0012)
argument-hint: <meeting-dir> <question>
---

Arguments: `$ARGUMENTS`
The FIRST token is the meeting directory (relative to the acervo root); the REST
is the question.

You are Loro's meeting assistant (ADR-0012). Work ONLY inside that directory. Use
only your own Read/Write tools — do not call loro IPC and do NOT edit
`manifest.json` (the app owns it; editing here would race the atomic writer).

1. **Investigate the LOCAL context FIRST:** read `<dir>/reuniao.md` (the LIVE
   transcript), `<dir>/manifest.json` and the clearly relevant
   `contextos/<c>/context.md` — the LOCAL base is always the first source. Do not
   read another meeting's transcript or `brainstorming/` notes you were not pointed
   at (BR-8).
2. Answer the question OBJECTIVELY, grounded in what the meeting and the local base
   actually say. **ONLY AFTER** exhausting the local base, if evidence is still
   missing, you MAY search external sources (internet, MCP, anywhere), making clear
   what came from outside. If nothing settles it, say so plainly.
3. When a written artifact helps (a table, a short note), write it under
   `<dir>/artefatos/respostas/<slug>.md` and reference it from the answer.
4. Append ONE PII-free JSON line to `<dir>/auditoria.jsonl` (event `answer`, what
   you read/produced — never transcript text, PII or secrets: BR-8/BR-9).

Reply in English.

Rigor rules (ADR-0002 §5):
- **Never assume unstated premises.** Anything not in the base or in the request
  is an uncertainty: record it explicitly (hotspot/`?` or an "uncertainties"
  line in the answer) and, when the interaction allows, ask.
- **Efficient scanning:** to list/read many files, delegate reading to subagents
  (Task) on a fast model (e.g. Haiku) returning only the essentials; keep the
  main model for synthesis.
- **Cheap reading (ADR-0004):** start from `INDEX.md` and each `context.md`
  Summary (§0); locate stable IDs (`D-…`, `H-…`) via search and read only the
  needed section — the whole file is the last resort.
"#;

pub fn meeting_analyse_skill(lang: &str) -> &'static str {
    if lang == "en" {
        MEETING_ANALYSE_SKILL_EN
    } else {
        MEETING_ANALYSE_SKILL
    }
}
pub fn meeting_question_skill(lang: &str) -> &'static str {
    if lang == "en" {
        MEETING_QUESTION_SKILL_EN
    } else {
        MEETING_QUESTION_SKILL
    }
}

// ---- AI-assisted notes (/loro-note, ADR-0003 §5) ----
// Create a note from a prompt, or evolve an existing note — always confined to
// the non-versioned brainstorming world.
pub const LORO_NOTE_SKILL: &str = r#"---
description: Cria ou evolui uma nota de brainstorming a partir de um prompt (ADR-0003)
argument-hint: <pasta-notas-ou-nota.md> <prompt>
---

Argumentos: `$ARGUMENTS`
O PRIMEIRO token é o alvo (relativo à raiz do acervo); o RESTANTE é o prompt.

Você é o assistente de notas do Loro. Trabalhe SOMENTE dentro de `brainstorming/`
— nunca toque em `contextos/` (mundo versionado) nem em `manifest.json`.

- Alvo é uma PASTA (ex.: `brainstorming/<tema>/notas`): crie uma nota nova em
  markdown a partir do prompt. Nome do arquivo: kebab-case curto derivado do
  assunto, terminando em `.md`; NUNCA sobrescreva um arquivo existente (em
  colisão, acrescente um sufixo). Primeira linha = título (`# …`).
- Alvo é um ARQUIVO `.md`: leia a nota e aplique o prompt sobre ela (expandir,
  resumir, reestruturar, responder o que está anotado) editando o próprio
  arquivo; preserve o que o autor escreveu — evolua, não apague.
- Escreva no idioma do prompt, em markdown simples e objetivo.
- Local-first: fundamente-se nos `contextos/` do acervo (somente leitura)
  quando ajudar.

Regras de rigor (ADR-0002 §5):
- **Nunca assuma premissas** não declaradas: o que não estiver na base ou no
  prompt é incerteza — registre explicitamente na nota (linha `?`).
- **Varredura eficiente:** para ler muitos arquivos, delegue a leitura a
  subagentes (Task) num modelo rápido (ex. Haiku) retornando só o essencial;
  reserve o modelo principal para a síntese.
- **Leitura barata (ADR-0004):** comece pelo `INDEX.md` e pelo Sumário (§0) de
  cada `context.md`; localize IDs estáveis (`D-…`, `H-…`) com busca e leia
  somente a seção necessária — o arquivo inteiro é o último recurso.
"#;

pub const LORO_NOTE_SKILL_EN: &str = r#"---
description: Creates or evolves a brainstorming note from a prompt (ADR-0003)
argument-hint: <notes-folder-or-note.md> <prompt>
---

Arguments: `$ARGUMENTS`
The FIRST token is the target (relative to the acervo root); the REST is the prompt.

You are Loro's note assistant. Work ONLY inside `brainstorming/` — never touch
`contextos/` (the versioned world) nor `manifest.json`.

- Target is a FOLDER (e.g. `brainstorming/<topic>/notas`): create a new markdown
  note from the prompt. Filename: short kebab-case derived from the subject,
  ending in `.md`; NEVER overwrite an existing file (on collision, add a
  suffix). First line = title (`# …`).
- Target is a `.md` FILE: read the note and apply the prompt to it (expand,
  summarize, restructure, answer what is noted) editing the file in place;
  preserve what the author wrote — evolve, do not erase.
- Write in the prompt's language, in plain, objective markdown.
- Local-first: ground yourself on the acervo's `contextos/` (read-only) when
  it helps.

Rigor rules (ADR-0002 §5):
- **Never assume unstated premises.** Anything not in the base or in the prompt
  is an uncertainty: record it explicitly in the note (a `?` line).
- **Efficient scanning:** to read many files, delegate reading to subagents
  (Task) on a fast model (e.g. Haiku) returning only the essentials; keep the
  main model for synthesis.
- **Cheap reading (ADR-0004):** start from `INDEX.md` and each `context.md`
  Summary (§0); locate stable IDs (`D-…`, `H-…`) via search and read only the
  needed section — the whole file is the last resort.
"#;

pub fn loro_note_skill(lang: &str) -> &'static str {
    if lang == "en" {
        LORO_NOTE_SKILL_EN
    } else {
        LORO_NOTE_SKILL
    }
}

// ---- external-source sync (/loro-sync, ADR-0005/0006) ----
// Attaches an external item (never its full content) as a `ref` on a
// brainstorming note. Sources: drive (Gemini notes), slack (a channel
// message), jira (a ticket), confluence (a page) — each identified directly
// by the user (channel/key/title/link), never guessed. The command stays
// generic so a future source needs no rename, only a new branch here.
pub const LORO_SYNC_SKILL: &str = r#"---
description: Anexa um item externo (Drive/Slack/Jira/Confluence) como referência numa nota do acervo (ADR-0005/0006)
argument-hint: <fonte:drive|slack|jira|confluence> <alvo-nota-ou-tema> <identificador>
---

Argumentos: `$ARGUMENTS`
O PRIMEIRO token é a FONTE; o SEGUNDO é o ALVO (uma nota `.md` ou um tema de
brainstorming, relativo à raiz do acervo); o RESTO é o IDENTIFICADOR do item
na fonte — o formato depende da fonte (veja abaixo).

Você é o assistente de sincronização externa do Loro. Trabalhe SOMENTE dentro
de `brainstorming/` — nunca toque em `contextos/` (mundo versionado). Em toda
fonte, **NUNCA leia, baixe ou cole o conteúdo/corpo do item na nota** — só
título, link e data (BR-8); e **NUNCA anexe sem confirmação explícita do
usuário** sobre qual item é (BR-1).

Se a fonte não for uma das listadas no `argument-hint`, diga claramente que
ainda não é suportada e pare — não invente comportamento.

Fonte `drive` (notas do Gemini no Google Drive) — identificador OPCIONAL
(busca ou link):
1. Se o identificador for um LINK do Google Drive/Docs (começa com
   `https://docs.google.com/` ou `https://drive.google.com/`): pule a busca,
   vá direto para a confirmação usando só os metadados desse documento
   (título, dono).
2. Caso contrário, busque no Google Drive documentos cujo título contenha
   "Anotações do Gemini" (use o identificador, se houver, como palavra-chave
   adicional do título — ex. o nome da reunião). **A busca NUNCA deve
   restringir por dono do documento** (nada de `owner = 'me'`): reuniões
   compartilhadas por colegas têm dono diferente do usuário e PRECISAM
   aparecer no resultado. Se a busca inicial não encontrar o esperado, tente
   de novo com uma busca mais ampla antes de desistir.
3. Aceite um candidato SOMENTE se o título contiver "Anotações do Gemini" E
   (a pasta-mãe for "Meet Recordings" da conta atual OU o dono do documento
   for outra pessoa). Um documento compartilhado normalmente não expõe
   pasta-mãe nenhuma para quem não é dono — isso é esperado, não é motivo
   para rejeitar. Nunca infira pelo conteúdo do documento.
4. Liste os candidatos (título, data, dono) e peça confirmação. Se nada for
   encontrado, sugira rodar de novo passando um LINK direto como
   identificador. Ao confirmar, grave `tipo: drive`, `caminho: <link>`.

Fonte `slack` — identificador OBRIGATÓRIO: o nome do canal (ex. `#eng-loro`
ou `eng-loro`):
1. Use o conector do Slack disponível para ler as mensagens recentes desse
   canal (e fixadas/pinned, se houver).
2. Liste as mensagens candidatas (autor, data, um trecho curto só para
   identificação visual — não é para copiar na nota) e peça ao usuário para
   confirmar QUAL mensagem/thread representa a reunião ou decisão a anexar.
   Se o canal não existir ou não houver mensagens relevantes, diga isso
   claramente em vez de inventar uma.
3. Ao confirmar, grave `tipo: slack`, `caminho: <link permanente da
   mensagem/thread>` (o "copy link" do Slack). Nunca cole o texto da
   mensagem no corpo da nota.

Fonte `jira` — identificador OBRIGATÓRIO: a chave do ticket (ex. `PROJ-123`)
ou o link direto do ticket:
1. Use o conector do Jira/Atlassian disponível para buscar esse ticket
   exato pela chave (extraindo a chave do link, se um link foi passado).
2. Mostre o título/resumo e status do ticket encontrado e peça confirmação
   antes de anexar — mesmo sendo um identificador exato, confirme que é o
   ticket certo.
3. Ao confirmar, grave `tipo: jira`, `caminho: <link do ticket>`. Nunca cole
   a descrição/comentários do ticket na nota.

Fonte `confluence` — identificador OBRIGATÓRIO: o título exato da página ou
o link direto:
1. Se for um link, use-o direto. Se for um título, use o conector do
   Confluence/Atlassian disponível para buscar a página por esse título.
2. Se houver mais de uma página com título parecido, liste as candidatas
   (título, espaço, atualizado em) e peça confirmação de qual é a certa.
3. Ao confirmar, grave `tipo: confluence`, `caminho: <link da página>`.
   Nunca cole o conteúdo da página na nota.

Em qualquer fonte, ao confirmar: edite o arquivo `.md` da nota-alvo (crie uma
nova nota em `brainstorming/<tema>/notas/` se o alvo for um tema, seguindo o
mesmo front-matter das notas existentes) e acrescente ao `refs:` a entrada
correspondente.

Regras de rigor (ADR-0002 §5):
- **Nunca assuma premissas** não declaradas: o que não estiver confirmado pelo
  usuário é incerteza — pergunte, não adivinhe.
- **Varredura eficiente:** para ler muitos arquivos, delegue a leitura a
  subagentes (Task) num modelo rápido (ex. Haiku) retornando só o essencial;
  reserve o modelo principal para a síntese.
- **Leitura barata (ADR-0004):** comece pelo `INDEX.md` e pelo Sumário (§0) de
  cada `context.md`; localize IDs estáveis (`D-…`, `H-…`) com busca e leia
  somente a seção necessária — o arquivo inteiro é o último recurso.
"#;

pub const LORO_SYNC_SKILL_EN: &str = r#"---
description: Attaches an external item (Drive/Slack/Jira/Confluence) as a reference on an acervo note (ADR-0005/0006)
argument-hint: <source:drive|slack|jira|confluence> <target-note-or-topic> <identifier>
---

Arguments: `$ARGUMENTS`
The FIRST token is the SOURCE; the SECOND is the TARGET (a `.md` note or a
brainstorming topic, relative to the acervo root); the REST is the item's
IDENTIFIER in that source — the shape depends on the source (see below).

You are Loro's external-sync assistant. Work ONLY inside `brainstorming/` —
never touch `contextos/` (the versioned world). For every source, **NEVER
read, download, or paste the item's content/body into the note** — only
title, link, and date (BR-8); and **NEVER attach without the user's explicit
confirmation** of which item it is (BR-1).

If the source is not one of the ones listed in `argument-hint`, say clearly
that it is not supported yet and stop — do not invent behavior.

Source `drive` (Gemini notes on Google Drive) — identifier OPTIONAL (a search
keyword or a link):
1. If the identifier is a Google Drive/Docs LINK (starts with
   `https://docs.google.com/` or `https://drive.google.com/`): skip the
   search and go straight to confirmation using only that document's
   metadata (title, owner).
2. Otherwise, search Google Drive for documents whose title contains
   "Anotações do Gemini" (use the identifier, if given, as an extra title
   keyword — e.g. the meeting's name). **The search must NEVER filter by
   document owner** (no `owner = 'me'`): meetings shared by colleagues have a
   different owner than the current user and MUST show up in the results. If
   the first search does not find what is expected, retry with a broader
   search before giving up.
3. Accept a candidate ONLY if the title contains "Anotações do Gemini" AND
   (the parent folder is "Meet Recordings" on the current account OR the
   document's owner is someone else). A shared document typically exposes no
   parent folder at all to a non-owner — that is expected, not a reason to
   reject. Never infer from the document's content.
4. List the candidates (title, date, owner) and ask for confirmation. If
   nothing is found, suggest re-running with a direct link as the
   identifier. On confirmation, record `tipo: drive`, `caminho: <link>`.

Source `slack` — identifier REQUIRED: the channel name (e.g. `#eng-loro` or
`eng-loro`):
1. Use the available Slack connector to read that channel's recent messages
   (and pinned ones, if any).
2. List the candidate messages (author, date, a short excerpt for visual
   identification only — not to be copied into the note) and ask the user to
   confirm WHICH message/thread represents the meeting or decision to
   attach. If the channel does not exist or has no relevant messages, say so
   plainly instead of inventing one.
3. On confirmation, record `tipo: slack`, `caminho: <the message/thread's
   permanent link>` (Slack's "copy link"). Never paste the message text into
   the note's body.

Source `jira` — identifier REQUIRED: the ticket key (e.g. `PROJ-123`) or a
direct ticket link:
1. Use the available Jira/Atlassian connector to fetch that exact ticket by
   key (extracting the key from the link, if a link was given).
2. Show the found ticket's title/summary and status and ask for
   confirmation before attaching — even for an exact identifier, confirm it
   is the right ticket.
3. On confirmation, record `tipo: jira`, `caminho: <ticket link>`. Never
   paste the ticket's description/comments into the note.

Source `confluence` — identifier REQUIRED: the page's exact title or a
direct link:
1. If it is a link, use it directly. If it is a title, use the available
   Confluence/Atlassian connector to search for a page with that title.
2. If more than one page has a similar title, list the candidates (title,
   space, updated date) and ask which one is correct.
3. On confirmation, record `tipo: confluence`, `caminho: <page link>`. Never
   paste the page's content into the note.

For any source, on confirmation: edit the target note's `.md` file (create a
new note under `brainstorming/<topic>/notas/` if the target is a topic,
following the same front-matter as existing notes) and append the matching
entry to `refs:`.

Rigor rules (ADR-0002 §5):
- **Never assume unstated premises.** Anything not confirmed by the user is an
  uncertainty — ask, do not guess.
- **Efficient scanning:** to read many files, delegate reading to subagents
  (Task) on a fast model (e.g. Haiku) returning only the essentials; keep the
  main model for synthesis.
- **Cheap reading (ADR-0004):** start from `INDEX.md` and each `context.md`
  Summary (§0); locate stable IDs (`D-…`, `H-…`) via search and read only the
  needed section — the whole file is the last resort.
"#;

pub fn loro_sync_skill(lang: &str) -> &'static str {
    if lang == "en" {
        LORO_SYNC_SKILL_EN
    } else {
        LORO_SYNC_SKILL
    }
}

// ---- general Q&A over the knowledge base (ADR-0013) ----
//
// `/loro-ask` answers ANY question from the acervo's versioned contexts (the local
// knowledge base) FIRST, and only after that may use MCP connectors / external
// search — the same local-first rule as the meeting AI. It is not meeting-scoped and
// writes nothing: the answer appears in the terminal. Same terminal-Claude skill
// pattern as /loro-context and /loro-analyse.
pub const BRAIN_ASK_SKILL: &str = r#"---
description: Responde uma dúvida a partir dos contextos do acervo (base local) e, se preciso, MCP/externo
argument-hint: <pergunta>
---

Pergunta: `$ARGUMENTS`

Você é o consultor deste acervo. Responda a pergunta de forma OBJETIVA (prosa de
negócio, sem metodologia).

1. **Investigue PRIMEIRO no contexto LOCAL.** Leia os `contextos/<c>/context.md`
   relevantes — a FONTE OFICIAL DA VERDADE do negócio — escolhendo os contextos pelo
   tema da pergunta; consulte o `CHANGELOG.md` do contexto quando ajudar. A base
   local é sempre a primeira fonte.
2. **SOMENTE DEPOIS**, se a base local não resolver, você PODE usar os conectores
   MCP disponíveis ou uma busca externa — deixando claro o que veio de fora.
3. Responda citando quais contextos embasaram a resposta (ex.: `contextos/frota`).
   Se a base não resolver, diga isso claramente e aponte o hotspot (§6) relevante,
   se houver — uma dúvida em aberto é um bom candidato a virar reunião/RFC.

Não modifique arquivos (isto é uma consulta). Responda em pt-BR.

Regras de rigor (ADR-0002 §5):
- **Nunca assuma premissas** não declaradas. O que não estiver na base ou no
  pedido é incerteza: registre-a explicitamente (hotspot/`?` ou uma linha de
  "incertezas" na resposta) e, quando a interação permitir, pergunte.
- **Varredura eficiente:** para listar/ler muitos arquivos, delegue a leitura a
  subagentes (Task) com um modelo rápido (ex.: Haiku), recebendo só o essencial;
  reserve o modelo principal para a síntese.
- **Leitura barata (ADR-0004):** comece pelo `INDEX.md` e pelo Sumário (§0) de
  cada `context.md`; localize IDs estáveis (`D-…`, `H-…`) com busca e leia
  somente a seção necessária — o arquivo inteiro é o último recurso.
"#;

pub const BRAIN_ASK_SKILL_EN: &str = r#"---
description: Answers a question from the acervo's contexts (local base) and, if needed, MCP/external
argument-hint: <question>
---

Question: `$ARGUMENTS`

You are this acervo's consultant. Answer OBJECTIVELY (business prose, no methodology).

1. **Investigate the LOCAL context FIRST.** Read the relevant `contextos/<c>/context.md`
   — the business SOURCE OF TRUTH — choosing contexts by the question's topic; consult
   the context `CHANGELOG.md` when it helps. The local base is always the first source.
2. **ONLY AFTER**, if the local base does not settle it, you MAY use the available
   MCP connectors or an external search — making clear what came from outside.
3. Answer citing which contexts grounded it (e.g. `contextos/frota`). If the base does
   not settle it, say so plainly and point at the relevant hotspot (§6) if any.

Do not modify files (this is a query). Reply in English.

Rigor rules (ADR-0002 §5):
- **Never assume unstated premises.** Anything not in the base or in the request
  is an uncertainty: record it explicitly (hotspot/`?` or an "uncertainties"
  line in the answer) and, when the interaction allows, ask.
- **Efficient scanning:** to list/read many files, delegate reading to subagents
  (Task) on a fast model (e.g. Haiku) returning only the essentials; keep the
  main model for synthesis.
- **Cheap reading (ADR-0004):** start from `INDEX.md` and each `context.md`
  Summary (§0); locate stable IDs (`D-…`, `H-…`) via search and read only the
  needed section — the whole file is the last resort.
"#;

pub fn brain_ask_skill(lang: &str) -> &'static str {
    if lang == "en" {
        BRAIN_ASK_SKILL_EN
    } else {
        BRAIN_ASK_SKILL
    }
}

// ---- CODEOWNERS (who approves changes per context/domain) ----
// Generated commented so an unfilled file never blocks GitHub's owner checks;
// the user uncomments and fills @user / @org/team per context. Approval itself
// happens on GitHub (branch protection); Loro only reads the resulting status.
pub fn codeowners_template(contexts: &[String], lang: &str) -> String {
    let header = if lang == "en" {
        "# CODEOWNERS — who approves changes to each context (domain).\n\
# Each line maps a context folder to its owner(s) on GitHub; only they can\n\
# approve PRs (RFCs) touching that folder. Uncomment and set @user or @org/team.\n\n"
    } else {
        "# CODEOWNERS — quem aprova mudanças em cada contexto (domínio).\n\
# Cada linha mapeia uma pasta de contexto ao(s) seu(s) dono(s) no GitHub; só eles\n\
# podem aprovar PRs (RFCs) que tocam aquela pasta. Descomente e defina @usuario ou @org/time.\n\n"
    };
    let lines = contexts
        .iter()
        .map(|c| format!("# /contextos/{c}/    @owner"))
        .collect::<Vec<_>>()
        .join("\n");
    format!("{header}{lines}\n")
}

// ---- Pull Request template = the RFC body ----
pub const PR_TEMPLATE: &str = r#"## Resumo da mudança
<!-- O que muda e por quê, em 1–2 frases. -->

## Contexto afetado
<!-- Qual domínio/pasta (ex.: contextos/frota). -->

## O que muda no conhecimento
<!-- As alterações no context.md (seções 1–5). -->

## Entrada de CHANGELOG
<!-- A entrada datada correspondente (## AAAA-MM-DD — título). -->

## Hotspots
<!-- Hotspots resolvidos e/ou criados por esta mudança. -->

## Riscos e pendências
<!-- O que ainda fica em aberto. -->
"#;

pub const PR_TEMPLATE_EN: &str = r#"## Change summary
<!-- What changes and why, in 1–2 sentences. -->

## Affected context
<!-- Which domain/folder (e.g. contextos/frota). -->

## What changes in the knowledge
<!-- The edits to context.md (sections 1–5). -->

## CHANGELOG entry
<!-- The matching dated entry (## YYYY-MM-DD — title). -->

## Hotspots
<!-- Hotspots resolved and/or created by this change. -->

## Risks and open points
<!-- What remains open. -->
"#;

// ---- language selectors ----
pub fn context_template(lang: &str) -> &'static str {
    if lang == "en" {
        CONTEXT_TEMPLATE_EN
    } else {
        CONTEXT_TEMPLATE
    }
}
pub fn agents_template(contexts: &[String], lang: &str) -> String {
    if lang == "en" {
        agents_template_en(contexts)
    } else {
        brain_claude_template(contexts)
    }
}
pub fn brain_skill(lang: &str) -> &'static str {
    if lang == "en" {
        BRAIN_SKILL_EN
    } else {
        BRAIN_SKILL
    }
}
pub fn pr_template(lang: &str) -> &'static str {
    if lang == "en" {
        PR_TEMPLATE_EN
    } else {
        PR_TEMPLATE
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ADR-0002 §5 — every skill forbids unstated premises and instructs
    // fast-model subagent scanning for bulk file reading, in both languages.
    #[test]
    fn skills_forbid_assumptions_and_instruct_fast_scanning() {
        for lang in ["pt", "en"] {
            let (no_assume, fast) = if lang == "en" {
                ("Never assume unstated premises", "fast model")
            } else {
                ("Nunca assuma premissas", "modelo rápido")
            };
            for (name, body) in [
                ("brain", brain_skill(lang)),
                ("ask", brain_ask_skill(lang)),
                ("analyse", meeting_analyse_skill(lang)),
                ("answer", meeting_question_skill(lang)),
                ("note", loro_note_skill(lang)),
                ("sync", loro_sync_skill(lang)),
            ] {
                assert!(
                    body.contains(no_assume),
                    "{name}/{lang}: missing no-premise rule"
                );
                assert!(
                    body.contains(fast),
                    "{name}/{lang}: missing fast-scanning rule"
                );
            }
        }
    }

    // ADR-0002 §5 — the loop's rule 6 records doubt instead of guessing.
    #[test]
    fn agents_rule_records_doubt_instead_of_guessing() {
        let pt = agents_template(&["frota".into()], "pt");
        assert!(!pt.contains("escolher o mais provável"));
        assert!(pt.contains("NÃO assuma"));
        let en = agents_template(&["fleet".into()], "en");
        assert!(en.contains("do NOT assume"));
    }

    // ADR-0012: the terminal Claude runs `analyse`/`answer` skills that take the
    // meeting dir as an argument. Assert both render (both languages) with the
    // meeting-dir placeholder and the acervo-facing contract (read the live
    // stream, do NOT touch manifest.json, write to the fixed artefatos subtree).
    #[test]
    fn meeting_skills_render_with_meeting_dir_argument() {
        for lang in ["pt", "en"] {
            let analyse = meeting_analyse_skill(lang);
            let answer = meeting_question_skill(lang);
            // meeting-dir argument placeholder is present in both
            assert!(
                analyse.contains("$ARGUMENTS"),
                "analyse [{lang}] lacks $ARGUMENTS"
            );
            assert!(
                answer.contains("$ARGUMENTS"),
                "answer [{lang}] lacks $ARGUMENTS"
            );
            // reads the LIVE stream (reuniao.md + manifest.json)
            assert!(analyse.contains("reuniao.md") && analyse.contains("manifest.json"));
            assert!(answer.contains("reuniao.md") && answer.contains("manifest.json"));
            // never edits the manifest (avoids racing the app's atomic writer)
            let edict = if lang == "en" {
                "NOT edit"
            } else {
                "NÃO edite"
            };
            assert!(
                analyse.contains(edict),
                "analyse [{lang}] must forbid editing manifest"
            );
            assert!(
                answer.contains(edict),
                "answer [{lang}] must forbid editing manifest"
            );
            // analyse writes its findings under the fixed investigacoes subtree
            assert!(analyse.contains("artefatos/investigacoes/analise-"));
            assert!(analyse.contains("auditoria.jsonl"));
            // ADR-0013: analyse persists PII-free markers via the sidecar the app folds in
            assert!(analyse.contains("marcadores.jsonl"));
            // answer writes optional artifacts under respostas + audits
            assert!(answer.contains("artefatos/respostas/"));
            assert!(answer.contains("auditoria.jsonl"));
            // ADR-0012 is cited so the WHY is traceable
            assert!(analyse.contains("ADR-0012") && answer.contains("ADR-0012"));
            // ADR-0013: investigate the LOCAL context FIRST, external only AFTER
            let (first, only_after) = if lang == "en" {
                ("LOCAL context FIRST", "ONLY AFTER")
            } else {
                ("PRIMEIRO no contexto LOCAL", "SOMENTE DEPOIS")
            };
            assert!(
                analyse.contains(first) && analyse.contains(only_after),
                "analyse [{lang}] must be local-first"
            );
            assert!(
                answer.contains(first) && answer.contains(only_after),
                "answer [{lang}] must be local-first"
            );
            // never read another brainstorming's notes (renamed world, ADR-0013)
            assert!(analyse.contains("brainstorming/") && !analyse.contains("pessoal/"));
        }
    }

    // ADR-0013: /loro-ask answers ANY question from the contexts (local base)
    // FIRST, MCP/external only after — not meeting-scoped, writes nothing.
    #[test]
    fn brain_ask_skill_is_local_first_over_contexts() {
        for lang in ["pt", "en"] {
            let ask = brain_ask_skill(lang);
            assert!(ask.contains("$ARGUMENTS"));
            assert!(ask.contains("contextos/"));
            assert!(ask.to_lowercase().contains("mcp"));
            let (first, after) = if lang == "en" {
                ("LOCAL context FIRST", "ONLY AFTER")
            } else {
                ("PRIMEIRO no contexto LOCAL", "SOMENTE DEPOIS")
            };
            assert!(
                ask.contains(first) && ask.contains(after),
                "ask [{lang}] must be local-first"
            );
        }
    }

    // ADR-0004 — the context.md mold opens with a summary card (§0) and carries
    // stable, greppable IDs: decisions D-YYYY-MM-DD-<slug>, hotspots H-<n>.
    #[test]
    fn context_template_carries_summary_card_and_stable_ids() {
        for lang in ["pt", "en"] {
            let tpl = context_template(lang);
            let summary = if lang == "en" {
                "## 0 · Summary"
            } else {
                "## 0 · Sumário"
            };
            assert!(tpl.contains(summary), "context [{lang}] lacks summary card");
            assert!(
                tpl.contains("[!HOTSPOT] H-"),
                "context [{lang}] hotspot format lacks the H-<n> id"
            );
            assert!(
                tpl.contains("D-"),
                "context [{lang}] lacks the decision id convention"
            );
        }
    }

    // ADR-0004 — every skill teaches the cheap-reading protocol: INDEX.md first,
    // then the summary card, then targeted section reads via stable IDs.
    #[test]
    fn skills_teach_cheap_reading_protocol() {
        for lang in ["pt", "en"] {
            let summary = if lang == "en" { "Summary" } else { "Sumário" };
            for (name, body) in [
                ("brain", brain_skill(lang)),
                ("ask", brain_ask_skill(lang)),
                ("analyse", meeting_analyse_skill(lang)),
                ("answer", meeting_question_skill(lang)),
                ("note", loro_note_skill(lang)),
            ] {
                assert!(
                    body.contains("INDEX.md"),
                    "{name}/{lang}: missing INDEX.md-first reading rule"
                );
                assert!(
                    body.contains(summary),
                    "{name}/{lang}: missing summary-card reading rule"
                );
            }
        }
    }

    // ADR-0004 — AGENTS defines the reading protocol and the enriched INDEX.md
    // line (description + updated date + hotspot ids), so routing decides
    // without opening files.
    #[test]
    fn agents_defines_reading_protocol_and_enriched_index_line() {
        for lang in ["pt", "en"] {
            let agents = agents_template(&["frota".into()], lang);
            let (protocol, updated) = if lang == "en" {
                ("Efficient reading", "updated")
            } else {
                ("Leitura eficiente", "atualizado")
            };
            assert!(
                agents.contains(protocol),
                "agents [{lang}] lacks the reading-protocol section"
            );
            assert!(
                agents.contains(updated) && agents.contains("H-"),
                "agents [{lang}] lacks the enriched INDEX.md line format"
            );
            assert!(
                agents.contains("D-"),
                "agents [{lang}] lacks the decision id convention"
            );
        }
    }

    // ADR-0013: the loop skill is /loro-context (hyphen; a dot is not a valid
    // Claude Code command name), materialized as .claude/commands/loro-context.md.
    #[test]
    fn brain_context_skill_renamed_from_brain() {
        for lang in ["pt", "en"] {
            let agents = agents_template(&["frota".into()], lang);
            assert!(agents.contains("/loro-context"));
            assert!(agents.contains("loro-context.md"));
            // the bare old form is gone from the AGENTS skill reference
            assert!(!agents.contains("`/brain`"));
            assert!(!agents.contains("commands/brain.md"));
        }
    }

    // ADR-0006: the loop skill checks .loro/settings.json's autoContext before
    // creating a NEW context on its own — off means it must leave the item
    // pending instead of assuming, in both languages.
    #[test]
    fn loop_skill_respects_auto_context_setting() {
        for lang in ["pt", "en"] {
            let skill = brain_skill(lang);
            assert!(skill.contains(".loro/settings.json"));
            assert!(skill.contains("autoContext"));
        }
    }
}
